-- ============================================================================
-- SUPABASE WEBHOOK SETUP FOR LEAD EMAIL NOTIFICATIONS
-- ============================================================================
-- This script uses Supabase's built-in Webhook feature instead of net.http_post
-- Webhooks are the official way to call edge functions from database triggers
-- ============================================================================

-- Step 1: Create leads table (if it doesn't exist)
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone_number TEXT,
    brief_description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT email_format CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$')
);

-- Add indexes for common queries
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON public.leads(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_email ON public.leads(email);

-- ============================================================================
-- SETUP INSTRUCTIONS (DO NOT RUN AS SQL - MANUAL STEPS):
-- ============================================================================
--
-- 1. CREATE THE WEBHOOK (Manual Step via Supabase Dashboard):
--    Go to: Database → Webhooks → Create a new webhook
--
--    Webhook Configuration:
--    - Name: send-lead-email-notification
--    - Type: HTTP Request
--    - Method: POST
--    - URL: https://<YOUR_PROJECT_REF>.supabase.co/functions/v1/send-lead-email
--    - Events: INSERT on public.leads table
--    - Headers:
--      * Content-Type: application/json
--      * Authorization: Bearer <YOUR_SERVICE_ROLE_KEY>
--
--    Transform Function (JavaScript):
--    SELECT {
--      record: {
--        name: NEW.name,
--        email: NEW.email,
--        phone_number: NEW.phone_number,
--        brief_description: NEW.brief_description
--      }
--    };
--
-- 2. SET EDGE FUNCTION SECRETS (Manual Step via Supabase Dashboard):
--    Go to: Edge Functions → send-lead-email → Environment Variables
--
--    Add these secrets:
--    - GMAIL_USER: your_gmail@gmail.com
--    - GMAIL_APP_PASSWORD: your_16_char_app_password
--    - RECIPIENT_EMAIL: GreaterAikenIrrigation@gmail.com
--
-- 3. DEPLOY EDGE FUNCTION (Manual Step via CLI):
--    npx supabase functions deploy send-lead-email
--
-- 4. TEST THE SETUP:
--    INSERT INTO public.leads (name, email, phone_number, brief_description)
--    VALUES ('Test Lead', 'test@example.com', '555-123-4567', 'Test description');
--
--    Check your email for the notification!
--
-- ============================================================================

-- Enable Row Level Security (RLS) for the leads table
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Create policy to allow inserts (for your application)
CREATE POLICY "Allow anonymous insert" ON public.leads
    FOR INSERT
    TO anon
    WITH CHECK (true);

-- Create policy to allow reading (if needed for your app)
CREATE POLICY "Allow public read" ON public.leads
    FOR SELECT
    TO public
    USING (true);

-- Grant necessary permissions
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON TABLE public.leads TO anon, authenticated;

-- ============================================================================
-- TEST QUERY (Uncomment to test after webhook is set up):
-- ============================================================================
--
-- INSERT INTO public.leads (name, email, phone_number, brief_description)
-- VALUES (
--     'Test User',
--     'test@example.com',
--     '912-266-9697',
--     'Type: Botanical Garden. Detail: Test lead submission'
-- );
--
-- SELECT * FROM public.leads ORDER BY created_at DESC LIMIT 1;
-- ============================================================================
