-- ============================================================================
-- DATABASE TRIGGER ARCHITECTURE FOR LEAD EMAIL NOTIFICATIONS
-- ============================================================================
-- This script sets up:
-- 1. leads table (if not exists)
-- 2. HTTP extensions for calling edge functions
-- 3. PostgreSQL function to call edge function
-- 4. AFTER INSERT trigger to automatically send emails on new leads
-- ============================================================================

-- Step 1: Create leads table (if it doesn't exist)
CREATE TABLE IF NOT EXISTS public.leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone_number TEXT,
    brief_description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT email_format CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}$')
);

-- Add indexes for common queries
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON public.leads(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_email ON public.leads(email);

-- Step 2: Enable required extensions for HTTP requests
-- Note: In Supabase, the http extension is typically already available
-- If you get an error, the extension might need to be enabled via Supabase dashboard

-- Step 3: Create function to call the edge function
CREATE OR REPLACE FUNCTION public.send_lead_email_notification()
RETURNS TRIGGER AS $$
DECLARE
    edge_function_url TEXT;
    payload JSON;
    response JSON;
    http_result JSON;
    edge_function_name TEXT := 'send-lead-email';
    supabase_url TEXT;
BEGIN
    -- Construct the edge function URL
    -- In production, you should set this as an environment variable
    -- Format: https://<your-project-ref>.supabase.co/functions/v1/send-lead-email
    supabase_url := current_setting('app.supabase_url', true);
    
    IF supabase_url IS NULL THEN
        -- Fallback: Try to get from pg_settings or use a placeholder
        -- User should replace this with their actual Supabase project URL
        supabase_url := 'https://YOUR_PROJECT_REF.supabase.co';
    END IF;
    
    edge_function_url := supabase_url || '/functions/v1/' || edge_function_name;
    
    -- Construct the payload matching the edge function's expected format
    -- Edge function expects: { "record": { name, email, phone_number, brief_description } }
    payload := json_build_object(
        'record', json_build_object(
            'name', NEW.name,
            'email', NEW.email,
            'phone_number', NEW.phone_number,
            'brief_description', NEW.brief_description
        )
    );
    
    -- Log the attempt
    RAISE LOG 'Attempting to call edge function for lead: % (email: %)', NEW.name, NEW.email;
    
    -- Call the edge function using net.http_post
    -- This is the Supabase-specific function for making HTTP requests
    BEGIN
        SELECT net.http_post(
            url := edge_function_url,
            headers := json_build_object(
                'Content-Type', 'application/json',
                'Authorization', 'Bearer ' || current_setting('app.service_role_key', true)
            ),
            body := payload,
            timeout_milliseconds := 10000
        ) INTO http_result;
        
        -- Log success
        RAISE LOG 'Edge function called successfully for lead: %. Response: %', NEW.name, http_result;
        
    EXCEPTION
        WHEN OTHERS THEN
            -- Log error but don't fail the insert
            RAISE LOG 'Failed to call edge function for lead: % (email: %). Error: %', 
                NEW.name, NEW.email, SQLERRM;
            
            -- Store the error in a notification queue or log table if needed
            -- For now, we just log and continue
    END;
    
    -- Return the NEW row to allow the insert to proceed
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Step 4: Create the AFTER INSERT trigger
-- This trigger fires after a new lead is inserted and attempts to send an email
DROP TRIGGER IF EXISTS trigger_send_lead_email ON public.leads;

CREATE TRIGGER trigger_send_lead_email
    AFTER INSERT ON public.leads
    FOR EACH ROW
    EXECUTE FUNCTION public.send_lead_email_notification();

-- ============================================================================
-- OPTIONAL: Helper tables/functions for error tracking
-- ============================================================================

-- Create a table to track edge function call failures (optional but recommended)
CREATE TABLE IF NOT EXISTS public.edge_function_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT REFERENCES public.leads(id),
    edge_function_name TEXT NOT NULL,
    status TEXT NOT NULL, -- 'success', 'failed', 'timeout'
    request_payload JSONB,
    response_payload JSONB,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Improved function with error logging
CREATE OR REPLACE FUNCTION public.send_lead_email_notification_with_logging()
RETURNS TRIGGER AS $$
DECLARE
    edge_function_url TEXT;
    payload JSON;
    http_result JSON;
    edge_function_name TEXT := 'send-lead-email';
    supabase_url TEXT;
    log_id BIGINT;
BEGIN
    -- Get Supabase URL
    supabase_url := current_setting('app.supabase_url', true);
    
    IF supabase_url IS NULL THEN
        supabase_url := 'https://YOUR_PROJECT_REF.supabase.co';
    END IF;
    
    edge_function_url := supabase_url || '/functions/v1/' || edge_function_name;
    
    -- Construct payload
    payload := json_build_object(
        'record', json_build_object(
            'name', NEW.name,
            'email', NEW.email,
            'phone_number', NEW.phone_number,
            'brief_description', NEW.brief_description
        )
    );
    
    -- Try to call edge function
    BEGIN
        SELECT net.http_post(
            url := edge_function_url,
            headers := json_build_object(
                'Content-Type', 'application/json',
                'Authorization', 'Bearer ' || current_setting('app.service_role_key', true)
            ),
            body := payload,
            timeout_milliseconds := 10000
        ) INTO http_result;
        
        -- Log success
        INSERT INTO public.edge_function_logs (
            lead_id, edge_function_name, status, request_payload, response_payload
        ) VALUES (
            NEW.id, edge_function_name, 'success', payload, http_result
        );
        
        RAISE LOG 'Edge function called successfully for lead: %', NEW.name;
        
    EXCEPTION
        WHEN OTHERS THEN
            -- Log failure
            INSERT INTO public.edge_function_logs (
                lead_id, edge_function_name, status, request_payload, error_message
            ) VALUES (
                NEW.id, edge_function_name, 'failed', payload, SQLERRM
            );
            
            RAISE LOG 'Failed to call edge function for lead: %. Error: %', NEW.name, SQLERRM;
    END;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Step 5: Test query to verify the setup
-- Uncomment and run to test:

-- Insert a test lead (this will trigger the edge function)
-- INSERT INTO public.leads (name, email, phone_number, brief_description)
-- VALUES (
--     'Test Lead',
--     'test@example.com',
--     '555-123-4567',
--     'This is a test lead to verify the trigger works'
-- );

-- Check if the lead was inserted
-- SELECT * FROM public.leads ORDER BY created_at DESC LIMIT 1;

-- Check edge function logs (if using logging version)
-- SELECT * FROM public.edge_function_logs ORDER BY created_at DESC LIMIT 1;

-- ============================================================================
-- SETUP INSTRUCTIONS:
-- ============================================================================
-- 1. Replace 'YOUR_PROJECT_REF' with your actual Supabase project reference
--    You can find this in your Supabase project settings
-- 2. Set the following environment variables in Supabase (via Dashboard > Settings > Environment Variables):
--    - app.supabase_url: Your Supabase project URL
--    - app.service_role_key: Your Supabase service role key (BE CAREFUL - this has full access)
-- 3. Ensure your edge function 'send-lead-email' is deployed
-- 4. Test by inserting a lead and checking the logs
-- 5. If using the logging version, replace the trigger:
--    DROP TRIGGER trigger_send_lead_email ON public.leads;
--    CREATE TRIGGER trigger_send_lead_email
--        AFTER INSERT ON public.leads
--        FOR EACH ROW
--        EXECUTE FUNCTION public.send_lead_email_notification_with_logging();
-- ============================================================================

-- Enable Row Level Security (RLS) for the leads table
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Create policy to allow inserts (for your application)
CREATE POLICY "Allow anonymous insert" ON public.leads
    FOR INSERT
    TO anon
    WITH CHECK (true);

-- Create policy to allow reading (if needed for your app)
CREATE POLICY "Allow public read" ON public.leads
    FOR SELECT
    TO public
    USING (true);

-- Grant necessary permissions
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON TABLE public.leads TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.send_lead_email_notification() TO anon, authenticated;
